---
title: "Assignment 1: Introduction"
author: "Jess Ozog"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: Last semester, I took ENV710 - Applied Data Analytics. That course was my first introduction to R and was very helpful in gaining a better understanding of statistical analysis. I have never used Git before. 

2. Are there any components of the course about which you feel confident?

> Answer: I am somewhat confident in my R skills, however, I have never used R for program applications, rather I have only used R for statistical analysis. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am somewhat apprehensive about keeping everything organized and making sure I know my file structure. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/jozog13/Environmental_Data_Analytics_2022



